name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-26, ubuntu-26.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Build and test
        shell: bash
        run: |
          cmake -B build .
          cmake --build build && build/strzcpy_tests

  build-windows:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v7
      - name: Build and test
        shell: bash
        run: |
          cmake -B build .
          cmake --build build && build/Debug/strzcpy_tests.exe
